version: "3.8"

services:
  backend:
    build: .
    container_name: ticket-concert-be
    restart: always
    ports:
      - "5000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ticket-concert-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketdb
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
